### ISSUE TITLE
Hoodies EPIC

### ISSUE THREAD

**Issue by nicolepilli** [NicolePilli-org/test-repo#21]
I'd like to: Redeem a hoodie, pay for it, and ship it to me

Stories:
- [ ] #22
- [ ] #23
- [ ] how payment information
- [ ] connect to metamask or through visa
- [ ] on chain blah blah
- [ ] shipping info (includes validations)
- [ ] manual validation of addresses

I will test this by:
unit test
manual test

Things to note:
we need to ... etc etc. to consider this this and this
